In [44]:
import pandas as pd

In [45]:
#data1 = pd.read_csv(raw_data1, usecols = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 16])
#data2 = pd.read_csv(raw_data2, usecols = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 16])

data1 = pd.read_csv('../../data/fsa_2007-2016.csv', usecols = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 16])
data2 = pd.read_csv('../../data/fsa_2017-2018.csv', usecols = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 16])

  # Specifies the order the columns should appear in
column_order = ['SCHOOL_YEAR',
                 'DATA_LEVEL',
                 'PUBLIC_OR_INDEPENDENT',
                 'DISTRICT_NUMBER',
                 'DISTRICT_NAME',
                 'SCHOOL_NUMBER',
                 'SCHOOL_NAME',
                 'SUB_POPULATION',
                 'FSA_SKILL_CODE',
                 'GRADE',
                 'NUMBER_EXPECTED_WRITERS',
                 'NUMBER_WRITERS',
                 'SCORE']
  
  # Reorders the columns in the dataframes so that they're in the same order
data1 = data1.reindex(columns = column_order)
data2 = data2.reindex(columns = column_order)
  
  # Stack the dataframes to make one master data file
raw_data = pd.concat([data1, data2])
  
  # Tidies the column names so that they're all lowercase
raw_data.columns = map(str.lower, raw_data.columns)

  
  # Splits the school_year into year_start and year_end
years = raw_data['school_year'].str.split("/", n = 1, expand = True)
raw_data['year_start'] = years[0]
raw_data['year_end'] = years[1]
raw_data.drop(columns = ['school_year'], inplace = True)

  # Removes all rows without FSA score data
clean_data = raw_data[raw_data.score != 'Msk']
clean_data = clean_data.dropna(subset=['score'])

  # Reformats the columns to the right datatypes
clean_data.score = pd.to_numeric(clean_data.score)
clean_data.year_start = pd.to_numeric(clean_data.year_start)
clean_data.year_end = pd.to_numeric(clean_data.year_end)
clean_data.number_expected_writers = pd.to_numeric(clean_data.number_expected_writers)
clean_data.number_writers = pd.to_numeric(clean_data.number_writers)

clean_data = clean_data[clean_data.number_writers != 0]

# Keep only the school-level data (remove Provincial and District summary rows)
clean_data = clean_data[clean_data.data_level == 'SCHOOL LEVEL']

# Changes 

  
clean_data.head()

,data_level,public_or_independent,district_number,district_name,school_number,school_name,sub_population,fsa_skill_code,grade,number_expected_writers,number_writers,score,year_start,year_end
4971,SCHOOL LEVEL,BC Public School,5.0,Southeast Kootenay,501007.0,Jaffray Elem-Jr Secondary,ALL STUDENTS,Numeracy,4,18,18,464.27778,2007,2008
4975,SCHOOL LEVEL,BC Public School,5.0,Southeast Kootenay,501007.0,Jaffray Elem-Jr Secondary,NON ABORIGINAL,Numeracy,4,16,16,468.87500,2007,2008
4976,SCHOOL LEVEL,BC Public School,5.0,Southeast Kootenay,501007.0,Jaffray Elem-Jr Secondary,NON ENGLISH LANGUAGE LEARNER,Numeracy,4,18,18,464.27778,2007,2008
4978,SCHOOL LEVEL,BC Public School,5.0,Southeast Kootenay,501007.0,Jaffray Elem-Jr Secondary,ALL STUDENTS,Numeracy,4,18,18,531.55556,2008,2009
4981,SCHOOL LEVEL,BC Public School,5.0,Southeast Kootenay,501007.0,Jaffray Elem-Jr Secondary,NON ABORIGINAL,Numeracy,4,18,18,531.55556,2008,2009

In [46]:
clean_data = clean_data.replace("BC PUBLIC SCHOOL", "BC Public School")
clean_data = clean_data.replace("BC INDEPENDENT SCHOOL", "BC Independent School")

In [48]:
clean_data.reset_index()
#clean_data.drop(columns = ['index'], inplace = True)

,index,data_level,public_or_independent,district_number,district_name,school_number,school_name,sub_population,fsa_skill_code,grade,number_expected_writers,number_writers,score,year_start,year_end
0,4971,SCHOOL LEVEL,BC Public School,5.0,Southeast Kootenay,501007.0,Jaffray Elem-Jr Secondary,ALL STUDENTS,Numeracy,4,18,18,464.27778,2007,2008
1,4975,SCHOOL LEVEL,BC Public School,5.0,Southeast Kootenay,501007.0,Jaffray Elem-Jr Secondary,NON ABORIGINAL,Numeracy,4,16,16,468.87500,2007,2008
2,4976,SCHOOL LEVEL,BC Public School,5.0,Southeast Kootenay,501007.0,Jaffray Elem-Jr Secondary,NON ENGLISH LANGUAGE LEARNER,Numeracy,4,18,18,464.27778,2007,2008
3,4978,SCHOOL LEVEL,BC Public School,5.0,Southeast Kootenay,501007.0,Jaffray Elem-Jr Secondary,ALL STUDENTS,Numeracy,4,18,18,531.55556,2008,2009
4,4981,SCHOOL LEVEL,BC Public School,5.0,Southeast Kootenay,501007.0,Jaffray Elem-Jr Secondary,NON ABORIGINAL,Numeracy,4,18,18,531.55556,2008,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329298,107963,SCHOOL LEVEL,BC Independent School,NaN,Chief & Council of Gwa'sala-'Nakwaxda'xw (IATH...,8597142.0,Gwa'sala-'Nakwaxda'xw School,ABORIGINAL,Writing,7,13,10,2.10000,2018,2019
329299,107964,SCHOOL LEVEL,BC Independent School,NaN,Chief & Council of Gwa'sala-'Nakwaxda'xw (IATH...,8597142.0,Gwa'sala-'Nakwaxda'xw School,NON ENGLISH LANGUAGE LEARNER,Writing,7,13,10,2.10000,2018,2019
329300,107986,SCHOOL LEVEL,BC Independent School,NaN,Nak'al Bun Education Society (IATHNBR:411),9197495.0,Nak'albun Elementary School,ALL STUDENTS,Writing,7,15,14,2.00000,2018,2019
329301,107989,SCHOOL LEVEL,BC Independent School,NaN,Nak'al Bun Education Society (IATHNBR:411),9197495.0,Nak'albun Elementary School,ABORIGINAL,Writing,7,13,12,2.00000,2018,2019
329302,107991,SCHOOL LEVEL,BC Independent School,NaN,Nak'al Bun Education Society (IATHNBR:411),9197495.0,Nak'albun Elementary School,NON ENGLISH LANGUAGE LEARNER,Writing,7,15,14,2.00000,2018,2019

In [34]:
clean_data.data_level.unique()

array(['SCHOOL LEVEL'], dtype=object)

In [35]:
clean_data.public_or_independent.unique()

array(['BC Public School', 'BC Independent School'], dtype=object)

In [36]:
clean_data.school_number.unique()

array([ 501007.,  501009.,  501010., ..., 7373083., 7373084., 4296940.])

In [37]:
clean_data.school_name.unique()

array(['Jaffray Elem-Jr Secondary', 'Isabella Dicken Elementary',
       'Frank J Mitchell Elementary', ...,
       'Barriere Elementary-Secondary',
       'Hope Lutheran Christian - Pitt Meadows',
       'Witset Elementary & Secondary School'], dtype=object)

In [38]:
clean_data.sub_population.unique()

array(['ALL STUDENTS', 'NON ABORIGINAL', 'NON ENGLISH LANGUAGE LEARNER',
       'FEMALE', 'MALE', 'ABORIGINAL', 'ENGLISH LANGUAGE LEARNER',
       'SPECIAL NEEDS NO GIFTED'], dtype=object)

In [39]:
clean_data.fsa_skill_code.unique()

array(['Numeracy', 'Reading', 'Writing'], dtype=object)

In [40]:
clean_data.grade.unique()

array([4, 7])